development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
  database: todo
  host: localhost
  
test:
    adapter: mysql2
    encoding: utf8
    database: todo
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock

production:
      adapter: mysql2
      encoding: utf8
      database: todo
      pool: 5
      username: todo
      password: pass
